services:
  postgres:
   image: postgres:16
   container_name: incidentes_postgres
   environment:
    POSTGRES_DB: incidentes
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
   ports:
    - "5432:5432"
   volumes:
    - postgres_data:/var/lib/postgresql/data

  seguranca-app:
   build: .
   container_name: container_seguranca_java
   depends_on:
    - postgres
   ports:
    - "8080:8080"
   environment:
    SERVER_PORT: 8080
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/incidentes"
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: 1234
   volumes:
    - ./meus_logs_host:/logs/incidentes

volumes:
  postgres_data: